name: Show Pull Request Change Note

on: 
  pull_request_target:
      types: [opened, edited]

jobs:
  show-pull-request-change-note:
    name: Show Pull Request Change Note
    runs-on: ubuntu-latest
    steps:
      - name: Enable Debug Logging
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      - name: Update apt cache
        run: |
          echo "Updating apt cache..."
          sudo apt-get update

      - name: Use The Release Notes Manager Action
        uses: Ahmed-Khaled-dev/release-notes-manager@v1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          action-type: pr
          pull-request-number: ${{ github.event.pull_request.number }}
          pull-request-trigger-event: ${{ github.event.action }}
          github-repository: ${{ github.repository }}
