name: Show Pull Request Change Note

on: 
  pull_request_target:
      types: [opened, edited]

jobs:
  show-pull-request-change-note:
    name: Show Pull Request Change Note
    runs-on: ubuntu-latest
    steps:
      - name: Check current sources (debugging)
        run: cat /etc/apt/sources.list || echo "sources.list not found"
        
      - name: Reset apt sources list
        run: |
          sudo tee /etc/apt/sources.list <<EOF
          deb http://archive.ubuntu.com/ubuntu jammy main universe
          deb http://archive.ubuntu.com/ubuntu jammy-updates main universe
          deb http://security.ubuntu.com/ubuntu jammy-security main universe
          EOF

      - name: Update apt cache
        run: sudo apt-get update

      - name: Use The Release Notes Manager Action
        uses: Ahmed-Khaled-dev/release-notes-manager@v1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          action-type: pr
          pull-request-number: ${{ github.event.pull_request.number }}
          pull-request-trigger-event: ${{ github.event.action }}
          github-repository: ${{ github.repository }}
